root: true

env:
  browser: true
  es2021: true

overrides: []

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
  - plugin:promise/recommended
  - "@nuxtjs/eslint-config-typescript"

parserOptions:
  sourceType: module
  ecmaVersion: latest

plugins:
  - "@typescript-eslint"

ignorePatterns:
  - .output/**

rules:
  quotes:
    - error
    - double
  object-curly-spacing:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  func-call-spacing: off
  space-before-function-paren:
    - error
    - never
  vue/multi-word-component-names: off