# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"

  lane :deploy do
    sh("yarn", "generate:native")

    sh("yarn", "sync:ios")

    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
    )

    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "~/private_keys/AuthKey_#{ENV["APP_STORE_CONNECT_KEY_ID"]}.p8",
    )

    upload_to_app_store(
      skip_metadata: true,
      precheck_include_in_app_purchases: false,
      force: true,
    )
  end
end
