nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.1.1.cjs

injectEnvironmentFiles:
  - .env?
npmRegistries:
  //npm.pkg.github.com/:
    npmAuthToken: ${GH_PACKAGES_TOKEN-}
npmScopes:
  chika3742:
    npmRegistryServer: https://npm.pkg.github.com
