default_platform(:android)

platform :android do
  desc "Push a new build to Google Play"
  lane :deploy do
    increment_version_code(version_code: ENV["ANDROID_VERSION_CODE"])
    gradle(task: "bundleRelease")

    upload_to_play_store(
      track: "internal",
      skip_upload_apk: true,
      skip_upload_changelogs: true,
      skip_upload_metadata: true,
      release_status: "draft",
      mapping_paths: ["app/build/outputs/mapping/release/mapping.txt"],
    )
  end
end