root: true

env:
  es6: true
  node: true

overrides: []

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - "@nuxtjs/eslint-config-typescript"
  - ../../.eslintrc.yml

parser: "@typescript-eslint/parser"

parserOptions:
  project:
    - tsconfig.json
    - tsconfig.dev.json
  sourceType: module

ignorePatterns:
  - /lib/**/*
