name: Deploy to App Store / Google Play

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  VERSION_NUMBER_OFFSET: 8

jobs:
  deploy-android:
    name: Deploy to Google Play
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/nuxt/android/Gemfile
      WORKLOAD_IDENTITY_PROVIDER: projects/218237880785/locations/global/workloadIdentityPools/github-actions/providers/github
      SERVICE_ACCOUNT: fastlane-integration@mydatauploader.iam.gserviceaccount.com
      WORKLOAD_IDENTITY_AUDIENCE: https://github.com/chika3742
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4 # for android build
        with:
          distribution: zulu
          java-version: '17'

      - uses: ruby/setup-ruby@v1 # for fastlane
        with:
          ruby-version: 3.3

      - run: bundle install

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: nuxt/yarn.lock

      - run: yarn install
        working-directory: nuxt

      - name: Extract local.properties
        run: base64 -d <<< "${{ secrets.ANDROID_LOCAL_PROPERTIES_BASE64 }}" >> nuxt/android/local.properties

      - name: Extract keystore
        run: base64 -d <<< "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" > nuxt/android/gm.keystore

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          audience: ${{ env.WORKLOAD_IDENTITY_AUDIENCE }}

      - run: yarn deploy:android
        working-directory: nuxt
        env:

