name: Deploy to App Store / Google Play

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  VERSION_NUMBER_OFFSET: 8

jobs:
  deploy-android:
    name: Deploy to Google Play
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/nuxt/android/Gemfile
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4 # for android build
        with:
          distribution: zulu
          java-version: '17'

      - uses: ruby/setup-ruby@v1 # for fastlane
        with:
          ruby-version: 3.3

      - run: bundle install

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: nuxt/yarn.lock

      - run: yarn install
        working-directory: nuxt

      - run: yarn deploy:android
        working-directory: nuxt
        env:

