name: Lint & Test (Nuxt)

on:
  push:
  workflow_dispatch:

jobs:
  test-nuxt:
    name: Lint & Test (Nuxt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: nuxt/yarn.lock

      - run: yarn install
        working-directory: nuxt
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          TEST: true

      - run: npm run lint
        working-directory: nuxt

      - run: npm run test
        working-directory: nuxt
